#!/bin/sh -

FILEPATH="/Users/rafael/Dropbox/Apps/MoneyLog Cloud/txt/03632-8.txt"

if [ $# != 4 ]; then
	echo "Usage: `basename $0` <date> <value> <tag> \"description\""
	exit
fi

if [ $1 == "hj" ]; then
	hoje=`date "+%Y-%m-%d"`
else
	hoje=$1
fi

printf "\n$hoje\t$2\t$3|$4" >> $FILEPATH
